package com.duaaps.scanner;

import com.getcapacitor.BridgeActivity;

/**
 * Plain Capacitor activity.
 *
 * Camera permission is requested in exactly ONE place: the ML Kit BarcodeScanner
 * plugin, called from www/app.js after the PIN is accepted. The BarcodeScanner
 * plugin is auto-registered via capacitor.plugins.json (generated by `cap sync`),
 * so no manual registerPlugin() call is needed here.
 *
 * Do NOT add additional permission launchers here: Android only shows one
 * permission dialog at a time and a second concurrent request is auto-denied.
 */
public class MainActivity extends BridgeActivity {}
